# Site settings
title:          Papers
description:    "CV/PR/AI/ML/DL"
baseurl:        "/papers"
url:            "https://www.quxiaofeng.me"

# Author
author:
  name:         QU Xiaofeng
  url:          https://quxiaofeng.me
  email:        quxiaofeng@live.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
